routes/web.php
<?php



use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ColegiadoController;
use App\Http\Controllers\PagoController;
use App\Http\Controllers\ConceptoController;
use App\Http\Controllers\CursoController;
use App\Http\Controllers\MatriculaController;

use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RolController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//RUTAS PARA CERTIFICADOS
//usuario
Route::get('/cursosycertificados', [MatriculaController::class, 'index'])->name('cursosycertificados');
Route::get('/cursosycertificados/{id}', [MatriculaController::class, 'indexfilter'])->name('cursosycertificadosfiltro');
Route::get('/cursosycertificados/matricular/{id}', [MatriculaController::class, 'searchcourse'])->name('vistamatricular');
Route::post('/cursosycertificados/matricular/{id}', [MatriculaController::class, 'create'])->name('matricularparticipante');
Route::post('/cursosycertificados/matricular/nuevamatricula/{id}', [MatriculaController::class, 'createnew'])->name('matricularnuevo');
Route::post('/cursosycertificados/miscertificados', [MatriculaController::class, 'miscertificados'])->name('buscarcertificador');
Route::get('/certificado/pdf/{idcurso}/{idcolegiado}', [MatriculaController::class, 'certificadoPDF'])->name('certificadopdf');

Auth::routes();

Route::group(['middleware'=>['auth']],function (){
    //RUTAS PARA USUARIOS
    Route::resource('usuarios', UsuarioController::class);
    Route::resource('roles', RolController::class);

    //RUTAS PARA TRAMITES
    Route::resource('colegiado',ColegiadoController::class);
    Route::resource('caja', PagoController::class);
    Route::get('/concepto', [ConceptoController::class,'index'])->name('conceptos.index');
    Route::get('/concepto/edit/{id}', [ConceptoController::class,'edit'])->name('conceptos.edit');
    Route::put('/concepto/update/{id}', [ConceptoController::class,'update'])->name('conceptos.update');
    Route::post('/nuevoconcepto', [ConceptoController::class,'store'])->name('conceptos.store');
    Route::delete('/concepto/destroy/{id}', [ConceptoController::class,'destroy'])->name('conceptos.destroy');
    Route::get('/buscar/{dni}', [ColegiadoController::class,'buscardni'])->name('colegiado.buscar');

    Route::get('/tramites', function () {
        return view('tramites.index'); //REDERIZA VISTA
    })->name('tramites.index');

    Route::get('/tramites/prueba', function () {
        return view('tramites.prueba'); //REDERIZA VISTA
    })->name('tramites.prueba');


    //RUTAS PARA CERTIFICADOS
    //Admin
    Route::get('/certificados', [CursoController::class, 'index'])->name('certificados.index');
    Route::get('/certificados/crear', function () {
        return view('certificados.administrador.crearcurso');
    })->name('vistacrear');
    Route::post('/certificados/crear', [CursoController::class, 'create'])->name('crearcurso');
    Route::get('/certificados/editar/{id}', [CursoController::class, 'edit'])->name('editarcurso');
    Route::put('/certificados/editar/{id}', [CursoController::class, 'update'])->name('actualizarcurso');
    Route::delete('/certificados/{id}', [CursoController::class, 'destroy'])->name('eliminarcurso');
    Route::get('/certificados/acceder/{id}', [MatriculaController::class, 'show'])->name('accedercurso');
    Route::get('/certificados/acceder/matriculas/{id}', [MatriculaController::class, 'showcompetitors'])->name('mostrarparticipantes');
    Route::get('/certificados/acceder/ponentes/{id}', [MatriculaController::class, 'showspeakers'])->name('mostrarponentes');
    Route::put('/certificados/acceder/matriculas/{id}', [MatriculaController::class, 'assignedspeaker'])->name('asignarponente');
    Route::delete('/certificados/acceder/matriculas/{id}', [MatriculaController::class, 'destroy'])->name('eliminarparticipante');

    //RUTAS PARA VENTAS
    // Route::get('/ventas', function () {
    //     return view('ventas.index'); //REDERIZA VISTA
    // })->name('ventas.index');

    Route::get('/dashboard', function () {
        return view('dash.index'); //REDERIZA VISTA
    })->name('dash.index');;
});

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuarios = User::all();//User::paginate(5);
        //dd($usuarios);
        return view('usuarios.index',compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/usuarios/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
@stop

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <h1>USUARIOS</h1>
        </div>
        <div class="row justify-content-end">
            <button class="btn btn-primary mb-2" data-toggle="modal" data-target="#staticBackdrop">Nueva Pago</button>
        </div>
        <div class="table-responsive-md">
            <p>{{$usuarios}}</p>
            <table id="caja" class="table table-striped mt-2">
                <thead>
                <th>Id</th>
                <th>Nombre</th>
                <th>Email</th>
                </thead>
                <tbody>

                @foreach ($usuarios as $usuario)
                    <tr>
                        <td>{{ $usuario->id }}</td>
                        <td>{{ $usuario->name }}</td>
                        <td>{{ $usuario->email }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">NUEVO USUARIO</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('usuarios.store')}}">
                        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
                        <div class="row">
                            <div class="col-md-12 mb-3">
                                <label for="dni">
                                    Nombre
                                    <span style="color: red;">*</span>
                                </label>
                                <input type="text" name="nombre" class="form-control xd" placeholder="Ingrese Nombre" aria-label="Ingrese Nombre" id="nombre">

                                <label for="dni">
                                    Email
                                    <span style="color: red;">*</span>
                                </label>
                                <input type="text" name="nombre" class="form-control xd" placeholder="Ingrese Nombre" aria-label="Ingrese Nombre" id="nombre">

                                <label for="dni">
                                    Contraseña
                                    <span style="color: red;">*</span>
                                </label>
                                <input type="text" name="nombre" class="form-control xd" placeholder="Ingrese Nombre" aria-label="Ingrese Nombre" id="nombre">

                                <label for="dni">
                                    Confirmar contraseña
                                    <span style="color: red;">*</span>
                                </label>
                                <input type="text" name="nombre" class="form-control xd" placeholder="Ingrese Nombre" aria-label="Ingrese Nombre" id="nombre">


                            </div>
                        </div>
                    </form>
                </div>
                {{--<div class="modal-body">
                    <form action="{{route('caja.store')}}" id="crearPago" name="crearPago" class=""  url="javascript:void(0)" method="POST">
                        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
                        <div class="row">
                            <div class="col-md-12 mb-3">
                                <label for="dni">
                                    DNI
                                    <span style="color: red;">*</span>
                                </label>
                                <div class="input-group">
                                    --}}{{-- <form action=" {{ route("colegiado.buscar", '64694794') }} " method="get"> --}}{{--
                                    <input type="text" class="form-control xd" placeholder="Ingrese DNI" aria-label="Ingrese DNI" id="dni">
                                    <input type="text" name="dnia" id="dnia" class="form-control" hidden>
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button" id="buscarDNI" onclick="buscar(dni)">Buscar</button>
                                    </div>
                                </div>
                                <div id="messageEvento" style="color:salmon" hidden>
                                    Ingrese caracteres validos.
                                </div>
                                <div id="noEncontrado" style="color:salmon" hidden>
                                    Usuario no encontrado
                                </div>
                                <div id="errorEvento" class=""></div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="apaterno" class="form-label">
                                    Apellido Paterno:
                                    <span style="color: red;">*</span>
                                </label>
                                --}}{{-- {!! Form::text('evento',null,array('id'=>'evento', 'class'=>'form-control '.($errors->has('evento') ? 'is-invalid':''), 'onkeyup'=>'validarEvento()','onblur'=>'validarEvento()')) !!} --}}{{--
                                <input type="text" name="apaterno" id="apaterno" class="form-control" readonly>
                                --}}{{-- @error('evento')
                            <span class="invalid-feedback">
                                <strong> {{$message}} </strong>
                            </span>
                            @enderror --}}{{--
                                <div id="errorEvento" class=""></div>
                            </div>

                            <div class="col-md-6 mb-3">
                                <label for="amaterno" class="form-label">
                                    Apellido Materno:
                                    <span style="color: red;">*</span>
                                </label>
                                <input type="text" name="amaterno" id="amaterno" class="form-control" readonly>
                                <div id="errorEvento" class=""></div>
                            </div>

                            <div class="col-md-12 mb-3">
                                <label for="nombres" class="form-label">
                                    Nombres:
                                    <span style="color: red;">*</span>
                                </label>
                                <input type="text" name="nombres" id="nombres" class="form-control" readonly>
                                <div id="errorEvento" class=""></div>
                            </div>

                            <div class="col-md-12 mb-3">
                                <label for="evento" class="form-label">
                                    Observaciones:
                                    <span style="color: red;">*</span>
                                </label>
                                <textarea type="text" name="observaciones" id="observaciones" class="form-control" placeholder="Ingrese Observaciones"></textarea>
                                --}}{{-- @error('evento')
                            <span class="invalid-feedback">
                                <strong> {{$message}} </strong>
                            </span>
                            @enderror --}}{{--
                                <div id="errorEvento" class=""></div>
                            </div>
                            <div class="col-md-12">
                                <label for="" class="form-label">
                                    Concepto de Pago:
                                    <span style="color: red;">*</span>
                                </label>
                                <div class="row" id="divpagos" onchange="sumatotal()">
                                    <div class="col-9 input-group" id="divconceptos1" onchange="cambioPago(this)">
                                        <select class="col-9 custom-select mb-2" name="concepto[]">
                                            <option value="-1" selected>Selección concepto de pago</option>
                                            @foreach ($conceptos as $concepto)
                                                <option value="{{$concepto->id}}">{{$concepto->nombre}}</option>
                                            @endforeach
                                        </select>
                                        <input type="text" class="col-2 form-control" name="stotal" readonly>
                                        <button type="button" class="col-1 close form-control" aria-label="Close" onclick="prueba(this)">
                                            <span aria-hidden="true" class="text-danger">&times;</span>
                                        </button>
                                    </div>
                                    <div class="col">
                                        <button class="btn btn-warning float-right" type="button" onclick="addConcepto()">Agregar</button>
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <div class="col-md">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text text-success"><b>TOTAL: </b></span>
                                                <span class="input-group-text text-success">S/.</span>
                                            </div>
                                            <input type="text" class="form-control text-success text-center" id="total" readonly>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>--}}


                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-primary">Enviar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
@stop
@section('css')
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop